# 1.Create numpy array of size (2, 3) filled with zeros

In [ ]:
import numpy as np
np.zeros((2, 3))

# 2.Create numpy array of size(5, 1) filled with ones

In [3]:
np.ones((5, 1), dtype=int)

array([[1],
       [1],
       [1],
       [1],
       [1]])

# 3.Combine two numpy array (3, 2) + (2, 2) => (5, 2)

In [12]:
a = np.array([[1, 2], [3, 4], [5, 6]])
b = np.array([[7, 8], [9, 10]])
np.vstack((a, b))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

# 4.Convert 2D to 1D

In [5]:
a = np.array([[1, 2], [3, 4], [5, 6]])
b = np.array([[7, 8], [9, 10]])
c = np.vstack((a, b))
c.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# 5.Interchange two axis of an array

In [7]:
d = np.array([[1, 2, 3], [4, 5, 6]])
d.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

# 6. Create a (2, 3, 5) numpy array with random values

In [9]:
np.random.randint(0, 100, size=(2, 3, 5))

array([[[54, 89, 45, 91, 82],
        [14, 81, 62,  9, 12],
        [60, 42, 86, 20, 48]],

       [[71,  3, 30, 18, 69],
        [95, 23, 83, 99, 56],
        [50, 21, 20, 48, 22]]])